CREATE TABLE FISH_NAME_INFO(
    FISH_TYPE INTEGER NOT NULL,
    FISH_NAME VARCHAR(50) NOT NULL
);

INSERT INTO FISH_NAME_INFO(FISH_TYPE, FISH_NAME) VALUES 
(0, 'BASS'),
(1, "SNAPPER"),
(2, "ANCHOVY");
