CREATE TABLE ITEM_INFO(
    ITEM_ID INTEGER NOT NULL,
    ITEM_NAME VARCHAR(50) NOT NULL,
    RARITY VARCHAR(50) NOT NULL,
    PRICE INTEGER NOT NULL
);

INSERT INTO ITEM_INFO (ITEM_ID, ITEM_NAME, RARITY, PRICE) VALUES
(0, 'ITEM_A', 'RARE', 10000),
(1, 'ITEM_B', 'RARE', 9000),
(2, 'ITEM_C', 'LEGEND', 11000),
(3, 'ITEM_D', 'RARE', 10000),
(4, 'ITEM_E', 'RARE', 12000);