# https://school.programmers.co.kr/learn/courses/30/lessons/293259
# 잡은 물고기의 평균 길이 구하기 

# SOLUTION 1
WITH FISH AS (
    SELECT IFNULL(LENGTH,10) AS LENGTH
    FROM FISH_INFO 
)
SELECT ROUND(AVG(LENGTH),2) AS AVERAGE_LENGTH
FROM FISH;

# SOLUTION 2 
SELECT ROUND(AVG(IFNULL(LENGTH, 10)),2) AS AVERAGE_LENGTH
FROM FISH_INFO;