# https://school.programmers.co.kr/learn/courses/30/lessons/293260
# 월별 잡은 물고기 수 구하기 

# SOL
# 잡은 물고기가 없는 월은 출력하지 않음 
SELECT COUNT(ID) AS FISH_COUNT, MONTH(TIME) AS MONTH
FROM FISH_INFO
GROUP BY MONTH
ORDER BY MONTH;

# 잡은 물고기가 없는 월은 0으로 출력
WITH RECURSIVE MONTHS AS (
    SELECT 1 AS MONTH
    UNION ALL 
    SELECT MONTH+1 FROM MONTHS WHERE MONTH < 12
),
FISH_INFO_CTE AS (
    SELECT COUNT(ID) AS FISH_COUNT, MONTH(TIME) AS MONTH
    FROM FISH_INFO 
    GROUP BY MONTH
    ORDER BY MONTH
)

SELECT IFNULL(FIC.FISH_COUNT,0) AS FISH_COUNT, M.MONTH
FROM FISH_INFO_CTE AS FIC
RIGHT JOIN MONTHS AS M 
USING (MONTH);