# https://school.programmers.co.kr/learn/courses/30/lessons/301651
# 멸종위기의 대장균 찾기 
# ECOLI_DATA

WITH RECURSIVE ECOLI_DATA_GENERATION AS (
    # NON RECURSIVE
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    # RECURSIVE
    SELECT ED.ID, ED.PARENT_ID, GENERATION + 1
    FROM ECOLI_DATA AS ED
    INNER JOIN ECOLI_DATA_GENERATION AS G
    ON ED.PARENT_ID = G.ID
),
CHILD AS (
    SELECT PARENT_ID, COUNT(PARENT_ID) AS CHILD
    FROM ECOLI_DATA 
    GROUP BY PARENT_ID
    HAVING PARENT_ID IS NOT NULL
)
SELECT COUNT(ID) AS COUNT, GENERATION
FROM ECOLI_DATA_GENERATION AS A
LEFT JOIN CHILD AS B
ON A.ID = B.PARENT_ID
WHERE B.CHILD IS NULL
GROUP BY GENERATION;