# https://school.programmers.co.kr/learn/courses/30/lessons/276036
# 언어별 개발자 분류하기 
# SKILLCODES & DEVELOPERS

# 비트 연산자 이용해서 풀어야 할 듯 

# SOLUTION 1
WITH FRONTEND AS (
    SELECT CODE
    FROM SKILLCODES 
    WHERE CATEGORY = 'Front End'
),
PYTHON AS (
    SELECT CODE
    FROM SKILLCODES 
    WHERE NAME = 'Python'
),
CSHARP AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME = 'C#'
)
SELECT 
    CASE 
        WHEN SKILL_CODE & (SELECT SUM(CODE) FROM FRONTEND) AND SKILL_CODE & (SELECT CODE FROM PYTHON) THEN 'A'
        WHEN SKILL_CODE & (SELECT CODE FROM CSHARP) THEN 'B'
        WHEN SKILL_CODE & (SELECT SUM(CODE) FROM FRONTEND) THEN 'C'
    END AS GRADE,
    ID, EMAIL
FROM DEVELOPERS 
HAVING GRADE IS NOT NULL
ORDER BY GRADE ASC, ID ASC;


# SOLUTION 2 -> 오답!!!!!!!!!
WITH GRADE_A AS (
    # Front End + Python
    SELECT NAME, CATEGORY, CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End' OR NAME = 'Python'
),
GRADE_B AS (
    SELECT NAME, CATEGORY, CODE
    FROM SKILLCODES
    WHERE NAME = 'C#'
),
GRADE_C AS (
    SELECT NAME, CATEGORY, CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
),
DEVELOPERS_GRADE AS (
    SELECT ID, EMAIL,
        CASE
            WHEN SKILL_CODE & (SELECT SUM(CODE) FROM GRADE_A) THEN 'A'
            WHEN SKILL_CODE & (SELECT SUM(CODE) FROM GRADE_B) THEN 'B'
            WHEN SKILL_CODE & (SELECT SUM(CODE) FROM GRADE_C) THEN 'C'
            ELSE NULL
        END AS GRADE 
    FROM DEVELOPERS
)
SELECT GRADE, ID, EMAIL
FROM DEVELOPERS_GRADE
WHERE GRADE IS NOT NULL
ORDER BY GRADE ASC, ID ASC;