# https://school.programmers.co.kr/learn/courses/30/lessons/301646
# 특정 형질을 가지는 대장균 찾기 


WITH A AS (
    SELECT ID, GENOTYPE
    FROM ECOLI_DATA
    WHERE GENOTYPE & 2 = 0
)
SELECT COUNT(ID) AS COUNT
FROM A
WHERE GENOTYPE & POWER(2, (1-1)) = POWER(2, (1-1)) 
    OR GENOTYPE & POWER(2, (3-1)) = POWER(2, (3-1));


SELECT COUNT(ID) AS COUNT
FROM ECOLI_DATA
WHERE GENOTYPE & 2 = 0 AND (GENOTYPE & 4 = 4 OR GENOTYPE & 1 = 1);