# https://school.programmers.co.kr/learn/courses/30/lessons/273711
# 업그레이드 된 아이템 구하기 

WITH ITEMS AS (
    SELECT I.ITEM_ID, ITEM_NAME, I.RARITY, T.PARENT_ITEM_ID
    FROM ITEM_INFO AS I
    LEFT JOIN ITEM_TREE AS T
    USING (ITEM_ID)
),
RARES AS (
    SELECT ITEM_ID
    FROM ITEM_INFO 
    WHERE RARITY = 'RARE'
)
SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEMS AS I
WHERE I.PARENT_ITEM_ID IN (SELECT * FROM RARES)
ORDER BY ITEM_ID DESC;
