# https://school.programmers.co.kr/learn/courses/30/lessons/299305
# 대장균들의 자식의 수 구하기 

WITH PARENT AS (
SELECT PARENT_ID, COUNT(ID) AS COUNT
FROM `ECOLI_DATA`
GROUP BY `PARENT_ID`
)
SELECT ID, IFNULL(COUNT, 0) AS CHILD_COUNT
FROM `ECOLI_DATA` AS E
LEFT JOIN PARENT AS P
ON E.ID = P.PARENT_ID
ORDER BY ID;
