# https://school.programmers.co.kr/learn/courses/30/lessons/299310
# 연도별 대장균 크기의 편차 구하기 
# ECOLI_DATA

# SOLUTION 1
WITH MAXSIZE_OF_YEAR AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR
    ORDER BY YEAR ASC
),
ECOLI AS (
    SELECT MSOY.YEAR, (MSOY.MAX_SIZE - ED.SIZE_OF_COLONY) AS YEAR_DEV, ID
    FROM ECOLI_DATA AS ED
    LEFT JOIN MAXSIZE_OF_YEAR AS MSOY
    ON YEAR(ED.DIFFERENTIATION_DATE) = MSOY.YEAR
)
SELECT * 
FROM ECOLI
ORDER BY YEAR ASC, YEAR_DEV ASC;


# SOLUTION 2
WITH MAX_ECOLI AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR
    ORDER BY YEAR ASC
)
SELECT YEAR, (ME.MAX_SIZE - ED.SIZE_OF_COLONY) AS YEAR_DEV, ED.ID
FROM ECOLI_DATA AS ED
LEFT JOIN MAX_ECOLI AS ME
ON YEAR(ED.DIFFERENTIATION_DATE) = ME.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;


# SOLUTION 3
SELECT E.YEAR, (E.MAX_SIZE - E.SIZE_OF_COLONY) AS YEAR_DEV, E.ID
FROM (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, SIZE_OF_COLONY,
    MAX(SIZE_OF_COLONY) OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE)) AS MAX_SIZE, ID
    FROM ECOLI_DATA
) AS E
ORDER BY YEAR, YEAR_DEV ASC;
