# https://school.programmers.co.kr/learn/courses/30/lessons/273712
# 업그레이드 할 수 없는 아이템 구하기 

# SOLUTION 1
SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY
FROM ITEM_INFO AS II
LEFT JOIN ITEM_TREE AS IT 
USING (ITEM_ID)
WHERE ITEM_ID NOT IN (
    SELECT DISTINCT(PARENT_ITEM_ID)
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IS NOT NULL
)
ORDER BY ITEM_ID DESC;

# SOLUTION 2
WITH UPGRADABLE AS (
    SELECT DISTINCT(PARENT_ITEM_ID)
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IS NOT NULL
)
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO AS II
LEFT JOIN ITEM_TREE AS IT
USING (ITEM_ID)
WHERE ITEM_ID NOT IN (SELECT * FROM UPGRADABLE)
ORDER BY ITEM_ID DESC;