# https://school.programmers.co.kr/learn/courses/30/lessons/298518
# 특정 물고기를 잡은 총 수 구하기 

# SOLUTION 1
WITH FISH AS (
    SELECT FI.ID, FI.FISH_TYPE, FNI.FISH_NAME
    FROM `FISH_INFO` AS FI, `FISH_NAME_INFO` AS FNI
    WHERE FI.`FISH_TYPE` = FNI.`FISH_TYPE`
)
SELECT COUNT(ID) AS FISH_COUNT
FROM FISH 
WHERE FISH_NAME IN ("BASS", "SNAPPER");

# SOLUTION 2
SELECT COUNT(ID) AS FISH_COUNT
FROM FISH_INFO AS FI
JOIN FISH_NAME_INFO AS FNI USING (FISH_TYPE)
WHERE FNI.FISH_NAME IN ("BASS", "SNAPPER");